
name: Run Selenium Test

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: windows-latest
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-java
         with:
           java-version: "11"
           cache: maven
       - uses: owner/repo@main
       - run: mvn clean test