
name: Run Selenium Test

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: windows-latest
    steps:
       - uses: actions/checkout@v2
       - uses: karimAdelhafez/Blink_Unity_MVS_Scenario
         with:
           java-version: "11"
           cache: maven
       - uses: browser-actions/setup-chrome@latest
       - run: mvn clean test