
name: Run Selenium Test

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on:
    steps:

       - uses: actions/setup-java
         with:
           java-version: "11"
           cache: maven
       - uses: browser-actions/setup-chrome@latest
       - run: mvn clean test